### ISSUE TITLE
Help please, crash included.

### ISSUE THREAD

**Issue by Lion4K** [rwtema/extrautilities#1015]
Can you please help me?

I'm trying to update from "extrautils2-1.10.2-alpha-1.0.1.jar" to "extrautils2-1.10.2-alpha-1.1.0a.jar" and keep getting this error: http://pastebin.com/RS7DSCEy

**Comment by xChitose** [comment]
Did you get this error on ver. 1.0.1?

**Comment by Lion4K** [comment]
No. It was working fine, the error were after I upgraded.

**Comment by xChitose** [comment]
There seems to be a multiple number of things dealing with ver. 1.1.0a, so, I really recommend just rolling back until another update gets released.

**Comment by Lion4K** [comment]
Yeah, i did that. By the by what really changed from 101 to 110a?

**Comment by xChitose** [comment]
From what others have said, they've added in a quarrying system and the deep dark dimension, but these are just the most notable ones so far. 

Also, there's the wireless RF system.

More info here:

https://minecraft.curseforge.com/projects/extra-utilities/files/2334232

**Comment by RobertLSnead** [comment]
Having same issues!  It is causing errors, apparently removing optifine fixes the issue however, not sure I can live without it!  It also is causing issues with random things!  Reverting back to 1.0.1 fixes the problem!

[](https://github.com/SlimeKnights/TinkersConstruct/issues/2446)

**Comment by DatrixTHLK** [comment]
Optifine Preview Build C4 fixes some of these issues due to rendering

**Comment by Lion4K** [comment]
@DatrixTHLK Where do I get this C4 version?

**Comment by Lion4K** [comment]
@DatrixTHLK nvm just found it.

**Comment by Lion4K** [comment]
Working awesomely

**Comment by DatrixTHLK** [comment]
Glad you enjoy it. I had to find out the hard way also.
