### ISSUE TITLE
JEI is not showing some recipes

### ISSUE THREAD

**Issue by Lion4K** [rwtema/extrautilities#1020]
Like:
Magical wood
Golden Lasso

And possibly others, cant say for sure.

btw how do I craft the Lasso?

Recipe in FTB Wiki don't work

**Comment by Bluerobin427** [comment]
I was having this issue as well, looks like 1.1.0b fixes it.

**Comment by AlphaKintari** [comment]
Also, some recipes now require experience to craft. Both Magical wood and the lasso do.

**Comment by Lion4K** [comment]
Ok, but whats the recipe?, I can't use 110 either a, b, c. Its crashing my game.

**Comment by Bluerobin427** [comment]
If I remember correctly it's 4 string and 4 gold nuggets in a circle, alternating between string and nuggets. If it's not showing up in JEI it might not be buildable, though, depending where the bug is.

**Comment by Lion4K** [comment]
I think it is cuz the magical wood is not showing either and its craftable

**Comment by Bluerobin427** [comment]
Looks like this is addressed here: https://github.com/rwtema/extrautilities/issues/1003

**Comment by Lion4K** [comment]
yeah it was, and seems that 110b and c fixed it, still i cant use 110 its crashing my game

**Comment by Lion4K** [comment]
It worked. Thanks for the recipe:

http://prntscr.com/ct1q30

Takes 6Level to make

**Comment by Lion4K** [comment]
Working fine with 110c
